# Generated by Django 4.0.2 on 2022-07-27 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Spa', 'Spa'), ('Restaurant', 'Restaurant'), ('Room', 'Room'), ('Activity', 'Activity'), ('Pool', 'Pool')], max_length=200)),
                ('image', models.ImageField(upload_to='gallery')),
            ],
        ),
    ]
