# Generated by Django 4.0.2 on 2022-07-28 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_blog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('guest_count', models.IntegerField(default=2)),
                ('price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('room_size', models.DecimalField(decimal_places=2, max_digits=15)),
                ('availability', models.BooleanField(default=True)),
                ('image', models.ImageField(upload_to='rooms')),
            ],
        ),
    ]
